### ISSUE TITLE
jni: com.openalpr.jni.AlprException: Unable to parse ALPR results

### ISSUE THREAD

**Issue by aacanakin** [openalpr/openalpr#369]
I have a program that have a file chooser and gets the file from chooser. After getting mediaFile I'm calling jni library using the following code;
```java
try {
    AlprResults results = alpr.recognize(mediaFile.getPath());
    DefaultListModel defaultListModel = new DefaultListModel();
    if (!results.getPlates().isEmpty()) {
        defaultListModel.addElement(
            String.format(
                "%s %4.3f",
                results.getPlates().get(0).getBestPlate().getCharacters(),
                results.getPlates().get(0).getBestPlate().getOverallConfidence()
            )
        );
    }

    resultList.setModel(defaultListModel);
} catch (AlprException ae) {
    ae.printStackTrace();
}
```
However, it gives the following error;
```
OpenCV Error: Assertion failed (scaleFactor > 1 && image.depth() == CV_8U) in detectMultiScale, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/objdetect/src/cascadedetect.cpp, line 1081
Caught exception in OpenALPR recognize: /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/objdetect/src/cascadedetect.cpp:1081: error: (-215) scaleFactor > 1 && image.depth() == CV_8U in function detectMultiScale

com.openalpr.jni.AlprException: Unable to parse ALPR results
	at com.openalpr.jni.Alpr.recognize(Alpr.java:48)
	at ui.MainScreen$1.actionPerformed(MainScreen.java:122)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
```

The alpr binary works fine with the image. Can you help with the problem?
I'm using Ubuntu Mate 16.04LTS

**Comment by matthill** [comment]
It's failing an assertion that either:
1. The scale factor is <= 1.0 (corresponds to detection_iteration_increase in openalpr.conf)
2. The image has not been loaded properly as grayscale.

Have you modified openalpr.conf in any way?  If not, maybe try a different image.

**Comment by aacanakin** [comment]
I didn't change the config however, I have both the git repo build and apt package. When I run `alpr` cli tool, it works fine. What would be the right config to use?

**Comment by matthill** [comment]
Can you compile in Debug Mode (Uncomment this: https://github.com/openalpr/openalpr/blob/master/src/CMakeLists.txt#L3)

If you run your program through a debugger (e.g., gdb) you should be able to inspect the image at that point.  That assert is firing because something is wrong with the inputs.  Scale factor should be 1.1 if you're using the default config, and the image should be a grayscale image.
