### ISSUE TITLE
Unable to locate the OpenALPR library

### ISSUE THREAD

**Issue by federicoprimomo** [openalpr/openalpr#461]
I'm trying to test a simple program in python, and I get this error :

`Traceback (most recent call last):
  File "patente.py", line 4, in <module>
    alpr = Alpr("us", "/usr/local/share/openalpr/config/openalpr.defaults.conf", "/usr/local/src/openalpr/runtime_data/")
  File "/usr/local/lib/python2.7/dist-packages/openalpr/openalpr.py", line 58, in __init__
    raise nex
OSError: Unable to locate the OpenALPR library. Please make sure that OpenALPR is properly installed on your system and that the libraries are in the appropriate paths.
Exception AttributeError: "Alpr instance has no attribute 'loaded'" in <bound method Alpr.__del__ of <openalpr.openalpr.Alpr instance at 0x76a295a8>> ignored`

Paths and config file seems to be ok.
Alpr is ok compiled, works great in command line.

**Comment by jiazhongchen** [comment]
exactly the same issue here.

**Comment by matthill** [comment]
The error is because Python can't find the dlls/so files for OpenALPR.  Can you run alpr from the command line?

**Comment by jiazhongchen** [comment]
thanks Matt, running under the command line works fine. also with python, importing the library seems working too. ( I am trying to run it on raspberry pi 3.)

**Comment by jiazhongchen** [comment]
$ alpr -c us image.jpg
plate0: 10 results
    - EA7THE	 confidence: 91.0578
    - EA7TBE	 confidence: 84.133
    - EA7T8E	 confidence: 83.0083
    - EA7TRE	 confidence: 82.7869
    - EA7TE	 confidence: 82.5961
    - EA7TME	 confidence: 80.2908
    - EA7TH6	 confidence: 77.0045
    - EA7THB	 confidence: 75.5779
    - EA7TH	 confidence: 74.6576
    - EA7TB6	 confidence: 70.0797

$python testalpr.py
Traceback (most recent call last):
  File "testalpr.py", line 3, in <module>
    alpr = Alpr("us", "/etc/openalpr/openalpr.conf", "/usr/local/src/openalpr/runtime_data")
  File "/usr/local/lib/python2.7/dist-packages/openalpr/openalpr.py", line 61, in __init__
    raise nex
OSError: Unable to locate the OpenALPR library. Please make sure that OpenALPR is properly installed on your system and that the libraries are in the appropriate paths.
Exception AttributeError: "Alpr instance has no attribute 'loaded'" in <bound method Alpr.__del__ of <openalpr.openalpr.Alpr instance at 0x76ab4760>> ignored

**Comment by alciomarhollanda** [comment]
Estou com esse problema também 

![image](https://user-images.githubusercontent.com/5420987/27922345-1a3e4318-6251-11e7-94c5-763f407ad04a.png)

**Comment by nicopereira** [comment]
I had the same problem, just be sure your python version is the correct architecture x86 or x64 same as openalpr.
I solved it installing x64 python

**Comment by rdarioduarte** [comment]
I'm getting the same issue using openAlpr 2.3.0 and python 3.7.1
I know this is old but, did anyone find the problem?

**Comment by HenryHengZJ** [comment]
> thanks Matt, running under the command line works fine. also with python, importing the library seems working too. ( I am trying to run it on raspberry pi 3.)
> 
> tested under command line:
> $ alpr -c us image.jpg
> plate0: 10 results
> 
> * EA7THE	confidence: 91.0578
> * EA7TBE	confidence: 84.133
> * EA7T8E	confidence: 83.0083
> * EA7TRE	confidence: 82.7869
> * EA7TE	confidence: 82.5961
> * EA7TME	confidence: 80.2908
> * EA7TH6	confidence: 77.0045
> * EA7THB	confidence: 75.5779
> * EA7TH	confidence: 74.6576
> * EA7TB6	confidence: 70.0797
> 
> with python shell, import works as well.
> $ python
> Python 2.7.9 (default, Sep 17 2016, 20:26:04)
> [GCC 4.9.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from openalpr import Alpr
> 
> seems exception happens when calling the Alpr constructor
> $python testalpr.py
> Traceback (most recent call last):
> File "testalpr.py", line 3, in
> alpr = Alpr("us", "/etc/openalpr/openalpr.conf", "/usr/local/src/openalpr/runtime_data")
> File "/usr/local/lib/python2.7/dist-packages/openalpr/openalpr.py", line 61, in init
> raise nex
> OSError: Unable to locate the OpenALPR library. Please make sure that OpenALPR is properly installed on your system and that the libraries are in the appropriate paths.
> Exception AttributeError: "Alpr instance has no attribute 'loaded'" in <bound method Alpr.del of <openalpr.openalpr.Alpr instance at 0x76ab4760>> ignored
> 
> Did a few search and a few people report the same issue, haven't find any clue yet.

@jiazhongchen any solution?

**Comment by alucard079** [comment]
@rdarioduarte any solution for that?

**Comment by hatamiarash7** [comment]
@alucard079 

Check your Python version and OpenALPR version to be same architectures

Install python 64-Bit and use 64-Bit version of library. It will work

**Comment by jerrychong25** [comment]
Hi @hatamiarash7,

I faced similar issue (https://github.com/openalpr/openalpr/issues/789) as per this issue. 

However, in my case, both Python and OpenALPR are in x64 version.

Could assist on this? 

Thanks.

**Comment by dhrumin75** [comment]
Also, Do we need a license key, i have followed the above steps, but i am getting 'Licensing Error'

**Comment by thiantat97** [comment]
> Hi @hatamiarash7,
> 
> I faced similar issue (#789) as per this issue.
> 
> However, in my case, both Python and OpenALPR are in x64 version.
> 
> Could assist on this?
> 
> Thanks.

@jerrychong25 have get the solution? if got can you share it? Thank you!

**Comment by jerrychong25** [comment]
> > Hi @hatamiarash7,
> > I faced similar issue (#789) as per this issue.
> > However, in my case, both Python and OpenALPR are in x64 version.
> > Could assist on this?
> > Thanks.
> 
> @jerrychong25 have get the solution? if got can you share it? Thank you!

@thiantat97 Unfortunately, I can't found any solution for this issue.

**Comment by hippoduck** [comment]
Still no solution? 

Or anyone have a better ALPR library?

**Comment by DSAishwaryaG** [comment]
Am struggling with the same issue.
Both python and alpr are x64,tried placing the file in C:\anaconda3\Lib\site-packages\openalpr 
Still the error persists.
Not understanding how to set the path of openalprpy.dll
Please help me resolve this.

**Comment by alexisgaziello** [comment]
Could the error be related to compiling the library and the python bindings being generated for python2?

Output of cmake:
...
-- Up-to-date: /usr/lib/libopenalprpy.so
-- Up-to-date: /usr/lib/python2.7/dist-packages/openalpr
-- Up-to-date: /usr/lib/python2.7/dist-packages/openalpr/openalpr.py
-- Up-to-date: /usr/lib/python2.7/dist-packages/openalpr/__init__.py
-- Up-to-date: /usr/lib/pkgconfig/openalpr.pc
...

**Comment by alexisgaziello** [comment]
Running `ldconfig` solved the problem for me.
