### ISSUE TITLE
'Alpr' object has no attribute 'loaded'

### ISSUE THREAD

**Issue by henriqueblobato** [openalpr/openalpr#533]
I believe its a very basic problem that everybody is having

I dont have the solution yet

Things I already did:

Install openalpr:
	sudo apt-get update && sudo apt-get install -y openalpr openalpr-daemon openalpr-utils libopenalpr-dev

Install wit the bash:
	bash <(curl http://deb.openalpr.com/install)
	git clone https://github.com/openalpr/openalpr.git
	cd openalpr/src/bindings/python/
	python setup.py install

Setup the environment
        > src
	> bindings
	> python
	sudo python<version> setup install

But at eclipse...
        from alpr import Alpr

Why this is happening?

**Comment by r1me** [comment]
`recognizeRawImage` is not available in release build (2.3.0) of Python wrapper. You will have to build master to get latest `openalprpy.dll` or remove definition of `recognizeRawImage` in `openalpr.py`

**Comment by tlawork** [comment]
Can you please create a release 2.3.1 which includes the definition of recognizeRawImage - please. I am having trouble compiling master manually.

**Comment by klwlau** [comment]
I have the same problem, anyone know how to solve it?

**Comment by sleebapaul** [comment]
@klwlau and @tlawork follow [this](https://github.com/openalpr/openalpr/issues/660) comment.

**Comment by klwlau** [comment]
@sleebapaul this solve my problem! thanks so much

**Comment by memoricab** [comment]
TBH not a nice solution but,

If you don't use recognize_ndarray; removing it from the source code worked for me as @r1me mentioned.
Because I used easiest way to install alpr libraries and I found that it was not updated as git master so there was missing function.

**Comment by HanyuuFurude** [comment]
I met with this problem when I was trying to run openalpr on raspberry and I haven't found a solution fits my problem yet.

**Comment by rishabhoswal** [comment]
Traceback (most recent call last):
  File "allapi.py", line 36, in <module>
    alpr = Alpr("us", "/etc/openalpr/openalpr.conf", "/usr/share/openalpr/runtime_data")
  File "/home/zm/code/main/detection/openCVYolo/alpr/python/openalpr/openalpr.py", line 85, in __init__
    self._recognize_raw_image_func = self._openalprpy_lib.recognizeRawImage
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libopenalprpy.so: undefined symbol: recognizeRawImage
Exception ignored in: <bound method Alpr.__del__ of <alpr.python.openalpr.openalpr.Alpr object at 0x7feb0a2c5048>>
Traceback (most recent call last):
  File "/home/zm/code/main/detection/openCVYolo/alpr/python/openalpr/openalpr.py", line 258, in __del__
    if self.is_loaded():
  File "/home/zm/code/main/detection/openCVYolo/alpr/python/openalpr/openalpr.py", line 135, in is_loaded
    if not self.loaded:
AttributeError: 'Alpr' object has no attribute 'loaded'

no solution seems to work in my case.
Help

**Comment by robertmzm** [comment]
> `recognizeRawImage` is not available in release build (2.3.0) of Python wrapper. You will have to build master to get latest `openalprpy.dll` or remove definition of `recognizeRawImage` in `openalpr.py`

once I get the binding setup, I commented out the following lines in /opt/anaconda3/lib/python3.7/site-packages/openalpr and it runs just fine

<img width="914" alt="Screen Shot 2021-02-20 at 12 42 11 PM" src="https://user-images.githubusercontent.com/15104191/108608062-35748d80-7379-11eb-8886-b7363308e0ab.png">

**Comment by jfernandz** [comment]
How can this be? I mean, ... how is possible than the python wrapper for `openalpr` is using features that aren't still released or aren't present in the last released version (2.3.0)?

I think this is a total incoordination and a big fail. Can somebody explain this?

I'd have to compile the master branch to get it working in a Raspberry Pi OS? How could I do this if there is not building instruction for Debian at all?

Is at least planned a newer release in a near future? There have not been any new release since 2016!
