### ISSUE TITLE
i install openalpr and when i try to npm install node-openalpr this error happens

### ISSUE THREAD

**Issue by FSBalbuena** [openalpr/openalpr#643]
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: node-openalpr package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties: 
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/util/versioning.js:220:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/util/versioning.js:279:5)
node-pre-gyp ERR! stack     at handle_gyp_opts (/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/util/handle_gyp_opts.js:59:27)
node-pre-gyp ERR! stack     at configure (/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/configure.js:12:5)
node-pre-gyp ERR! stack     at /home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/build.js:43:13
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/util/compile.js:85:9)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.13.0-37-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/.bin/node-pre-gyp" "install" "--build-from-source" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN watsi@1.0.0 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! node-openalpr@1.1.1 install: `node-pre-gyp install --build-from-source --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the node-openalpr@1.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-03-23T19_32_29_952Z-debug.log

**Comment by TiagoSilvaPereira** [comment]
+1

**Comment by rtalexk** [comment]
I have the exact same error:

```
npm i -S node-openalpr

> node-openalpr@1.1.1 install /home/alxgm/Documents/ProjectsVS/ALPR/node_modules/node-openalpr
> node-pre-gyp install --build-from-source --fallback-to-build

node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: node-openalpr package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (/home/alxgm/Documents/ProjectsVS/ALPR/node_modules/node-pre-gyp/lib/util/versioning.js:220:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/home/alxgm/Documents/ProjectsVS/ALPR/node_modules/node-pre-gyp/lib/util/versioning.js:279:5)
node-pre-gyp ERR! stack     at handle_gyp_opts (/home/alxgm/Documents/ProjectsVS/ALPR/node_modules/node-pre-gyp/lib/util/handle_gyp_opts.js:59:27)
node-pre-gyp ERR! stack     at configure (/home/alxgm/Documents/ProjectsVS/ALPR/node_modules/node-pre-gyp/lib/configure.js:12:5)
node-pre-gyp ERR! stack     at /home/alxgm/Documents/ProjectsVS/ALPR/node_modules/node-pre-gyp/lib/build.js:43:13
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/alxgm/Documents/ProjectsVS/ALPR/node_modules/node-pre-gyp/lib/util/compile.js:85:9)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.13.0-39-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/alxgm/Documents/ProjectsVS/ALPR/node_modules/.bin/node-pre-gyp" "install" "--build-from-source" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/alxgm/Documents/ProjectsVS/ALPR/node_modules/node-openalpr
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN ALPR@1.0.0 No description
npm WARN ALPR@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! node-openalpr@1.1.1 install: `node-pre-gyp install --build-from-source --fallback-to-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the node-openalpr@1.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alxgm/.npm/_logs/2018-04-28T02_13_22_674Z-debug.log
```

**Comment by bameyrick** [comment]
I had this issue too but I have a work around for now. I noticed in the node-openaplr package.json the dependency for node-pre-gyp points to the node-pre-gyp repository, which means it will pull in the latest version of node-pre-gyp, which is way ahead of the last commit made in the node-openaplr repository.

I've forked the node-openaplr repository and specified a commit hash on the node-pre-gyp dependency in the package.json, and then installed node-openaplr to my project using
`yarn add https://github.com/bameyrick/node-openalpr`

**Comment by axeless** [comment]
@bameyrick You could not write how to do this.

**Comment by KayhanB** [comment]
+1

**Comment by RichardKuduk** [comment]
Hi, any help would be great. I have installed yarn followed the instructions provided by @bameyrick and got following error: 
`pi@raspberrypi:/usr/local/src $ sudo yarn add https://github.com/bameyrick/node-openalpr
yarn add v1.13.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "node-pre-gyp@0.6.18" is missing a bundled dependency "nopt". This should be reported to the package maintainer.
warning "node-pre-gyp@0.6.18" is missing a bundled dependency "npmlog". This should be reported to the package maintainer.
warning "node-pre-gyp@0.6.18" is missing a bundled dependency "request". This should be reported to the package maintainer.
warning "node-pre-gyp@0.6.18" is missing a bundled dependency "semver". This should be reported to the package maintainer.
warning "node-pre-gyp@0.6.18" is missing a bundled dependency "tar". This should be reported to the package maintainer.
warning "node-pre-gyp@0.6.18" is missing a bundled dependency "tar-pack". This should be reported to the package maintainer.
warning "node-pre-gyp@0.6.18" is missing a bundled dependency "mkdirp". This should be reported to the package maintainer.
warning "node-pre-gyp@0.6.18" is missing a bundled dependency "rc". This should be reported to the package maintainer.
[4/4] Building fresh packages...
error /usr/local/src/node_modules/node-openalpr: Command failed.
Exit code: 1
Command: node-pre-gyp install --build-from-source --fallback-to-build
Arguments: 
Directory: /usr/local/src/node_modules/node-openalpr
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.18
node-pre-gyp info using node@11.2.0 | linux | arm
node-pre-gyp info build requesting source compile
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.2.0 | linux | arm
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.2.0 | linux | arm
gyp http GET https://nodejs.org/download/release/v11.2.0/node-v11.2.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v11.2.0/node-v11.2.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v11.2.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v11.2.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/src/node_modules/node-openalpr/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/11.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/11.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/11.2.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/src/node_modules/node-openalpr',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.2.0 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/usr/local/src/node_modules/node-openalpr/build'
  CXX(target) Release/obj.target/node_openalpr/src/node_openalpr.o
../src/node_openalpr.cc: In member function ‘virtual void LPRWorker::HandleOKCallback()’:
../src/node_openalpr.cc:112:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
    callback->Call (2, argv);
                           ^
In file included from ../src/node_openalpr.cc:5:0:
../../nan/nan.h:1674:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/node_openalpr.cc: In function ‘char* get(v8::Local<v8::Value>)’:
../src/node_openalpr.cc:127:38: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   v8::String::Utf8Value string (value);
                                      ^
In file included from /root/.node-gyp/11.2.0/include/node/v8.h:26:0,
                 from ../src/node_openalpr.cc:1:
/root/.node-gyp/11.2.0/include/node/v8.h:2992:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/11.2.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/node_openalpr.cc:133:9: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  return "";
         ^~
../src/node_openalpr.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Start(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node_openalpr.cc:141:45: warning: ‘double v8::Value::NumberValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  int instancesCount = info[2]->NumberValue ();
                                             ^
In file included from /root/.node-gyp/11.2.0/include/node/v8.h:26:0,
                 from ../src/node_openalpr.cc:1:
/root/.node-gyp/11.2.0/include/node/v8.h:2569:45: note: declared here
   V8_DEPRECATED("Use maybe version", double NumberValue() const);
                                             ^
/root/.node-gyp/11.2.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/node_openalpr.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE IdentifyLicense(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node_openalpr.cc:189:45: warning: ‘bool v8::Value::BooleanValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  bool detectRegion = info[3]->BooleanValue ();
                                             ^
In file included from /root/.node-gyp/11.2.0/include/node/v8.h:26:0,
                 from ../src/node_openalpr.cc:1:
/root/.node-gyp/11.2.0/include/node/v8.h:2568:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
                                           ^
/root/.node-gyp/11.2.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/node_openalpr.cc:194:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (int i = 0; i < regionsArray->Length (); i++) {
                  ~~^~~~~~~~~~~~~~~~~~~~~~~~~
../src/node_openalpr.cc:196:47: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int x = regionValues->Get (0)->Uint32Value ();
                                               ^
In file included from /root/.node-gyp/11.2.0/include/node/v8.h:26:0,
                 from ../src/node_openalpr.cc:1:
/root/.node-gyp/11.2.0/include/node/v8.h:2571:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/11.2.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/node_openalpr.cc:197:47: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int y = regionValues->Get (1)->Uint32Value ();
                                               ^
In file included from /root/.node-gyp/11.2.0/include/node/v8.h:26:0,
                 from ../src/node_openalpr.cc:1:
/root/.node-gyp/11.2.0/include/node/v8.h:2571:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/11.2.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/node_openalpr.cc:198:51: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int width = regionValues->Get (2)->Uint32Value ();
                                                   ^
In file included from /root/.node-gyp/11.2.0/include/node/v8.h:26:0,
                 from ../src/node_openalpr.cc:1:
/root/.node-gyp/11.2.0/include/node/v8.h:2571:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/11.2.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/node_openalpr.cc:199:52: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int height = regionValues->Get (3)->Uint32Value ();
                                                    ^
In file included from /root/.node-gyp/11.2.0/include/node/v8.h:26:0,
                 from ../src/node_openalpr.cc:1:
/root/.node-gyp/11.2.0/include/node/v8.h:2571:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/11.2.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/node_openalpr.node
g++: error: /usr/lib/libopenalpr.so: No such file or directory
node_openalpr.target.mk:130: recipe for target 'Release/obj.target/node_openalpr.node' failed
make: Leaving directory '/usr/local/src/node_modules/node-openalpr/build'
make: *** [Release/obj.target/node_openalpr.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--build-from-source" "--fallback-to-build" "--module=/usr/local/src/node_modules/node-openalpr/release/linux_arm/node_openalpr.node" "--module_name=node_openalpr" "--module_path=/usr/local/src/node_modules/node-openalpr/release/linux_arm"
gyp ERR! cwd /usr/local/src/node_modules/node-openalpr
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --fallback-to-build --module=/usr/local/src/node_modules/node-openalpr/release/linux_arm/node_openalpr.node --module_name=node_openalpr --module_path=/usr/local/src/node_modules/node-openalpr/release/linux_arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/src/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Linux 4.14.79-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/src/node_modules/node-openalpr/node_modules/.bin/node-pre-gyp" "install" "--build-from-source" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/src/node_modules/node-openalpr
node-pre-gyp ERR! node -v v11.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.18
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --fallback-to-build --module=/usr/local/src/node_modules/node-openalpr/release/linux_arm/node_openalpr.node --module_name=node_openalpr --module_path=/usr/local/src/node_modules/node-openalpr/release/linux_arm' (1)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`

**Comment by anshgupta1234** [comment]
@bameyrick , @axeless is asking how you did the commit hashing and stuff. Could you specify the information for me and him? Thanks a lot.

**Comment by bameyrick** [comment]
Oh yeah sure, it should just be:

```bash
npm i -S https://github.com/bameyrick/node-openalpr#b26a8b52f89796d64c86f24e42734e8a3ed77e2d
```

or if you're using yarn:
```bash
yarn add https://github.com/bameyrick/node-openalpr#b26a8b52f89796d64c86f24e42734e8a3ed77e2d
```

**Comment by elperez** [comment]
hello @bameyrick 

I have tried:
 i -S https://github.com/bameyrick/node-openalpr#b26a8b52f89796d64c86f24e42734e8a3ed77e2d

But I am getting:
../src/node_openalpr.cc:194:20: warning: comparison of integers of different signs:
      'int' and 'uint32_t' (aka 'unsigned int') [-Wsign-compare]
        for (int i = 0; i < regionsArray->Length (); i++) {
                        ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~
9 warnings generated.
  SOLINK_MODULE(target) Release/node_openalpr.node
clang: error: no such file or directory: '/usr/local/lib/libopenalpr.2.dylib'
make: *** [Release/node_openalpr.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kit.perez/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/kit.perez/.nvm/versions/node/v10.15.0/bin/node" "/Users/kit.perez/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--build-from-source" "--fallback-to-build" "--module=/Users/kit.perez/Documents/my_repo/servosec/anpr/node_modules/node-openalpr/release/darwin_x64/node_openalpr.node" "--module_name=node_openalpr" "--module_path=/Users/kit.perez/Documents/my_repo/servosec/anpr/node_modules/node-openalpr/release/darwin_x64"
gyp ERR! cwd /Users/kit.perez/Documents/my_repo/servosec/anpr/node_modules/node-openalpr
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/kit.perez/.nvm/versions/node/v10.15.0/bin/node /Users/kit.perez/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --fallback-to-build --module=/Users/kit.perez/Documents/my_repo/servosec/anpr/node_modules/node-openalpr/release/darwin_x64/node_openalpr.node --module_name=node_openalpr --module_path=/Users/kit.perez/Documents/my_repo/servosec/anpr/node_modules/node-openalpr/release/darwin_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/kit.perez/Documents/my_repo/servosec/anpr/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command "/Users/kit.perez/.nvm/versions/node/v10.15.0/bin/node" "/Users/kit.perez/Documents/my_repo/servosec/anpr/node_modules/.bin/node-pre-gyp" "install" "--build-from-source" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/kit.perez/Documents/my_repo/servosec/anpr/node_modules/node-openalpr
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.18
node-pre-gyp ERR! not ok
Failed to execute '/Users/kit.perez/.nvm/versions/node/v10.15.0/bin/node /Users/kit.perez/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --fallback-to-build --module=/Users/kit.perez/Documents/my_repo/servosec/anpr/node_modules/node-openalpr/release/darwin_x64/node_openalpr.node --module_name=node_openalpr --module_path=/Users/kit.perez/Documents/my_repo/servosec/anpr/node_modules/node-openalpr/release/darwin_x64' (1)
npm WARN anpr@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-openalpr@1.1.1 install: `node-pre-gyp install --build-from-source --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-openalpr@1.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
