### ISSUE TITLE
Library Import Problem (Python 3.7)

### ISSUE THREAD

**Issue by damirqa** [openalpr/openalpr#738]
Hello! I tried run my code for check working capacity
```
import openalpr
import sys
alpr = openalpr.Alpr("ru", "ru.conf", "runtime_data")
if not alpr.is_loaded():
    print("Error loading OpenALPR")
    sys.exit(1)
```
But i got errors:
```
C:\Users\kacer\AppData\Local\Programs\Python\Python37-32\python.exe C:/Users/kacer/Desktop/SRT/main.py
Traceback (most recent call last):
  File "C:\Users\kacer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openalpr\openalpr.py", line 48, in __init__
    self._openalprpy_lib = ctypes.cdll.LoadLibrary("openalprpy.dll")
  File "C:\Users\kacer\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\kacer\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Не найден указанный модуль

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/kacer/Desktop/SRT/main.py", line 4, in <module>
    alpr = openalpr.Alpr("ru", "ru.conf", "runtime_data")
  File "C:\Users\kacer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openalpr\openalpr.py", line 58, in __init__
    raise nex
OSError: Unable to locate the OpenALPR library. Please make sure that OpenALPR is properly installed on your system and that the libraries are in the appropriate paths.
Exception ignored in: <function Alpr.__del__ at 0x02CD76A8>
Traceback (most recent call last):
  File "C:\Users\kacer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openalpr\openalpr.py", line 222, in __del__
  File "C:\Users\kacer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openalpr\openalpr.py", line 118, in is_loaded
AttributeError: 'Alpr' object has no attribute '_is_loaded_func'

Process finished with exit code 1
```

How can this problem be solved?

**Comment by xtianhb** [comment]
Have you executed the setup.py script?
https://github.com/openalpr/openalpr/blob/master/src/bindings/python/setup.py
I think it is included in Windows Binaries also, in the pyton folder.

**Comment by soufianesabiri** [comment]
I have ran the setup.py but I still get the error : 
> AttributeError: 'Alpr' object has no attribute 'loaded'
Please help!

**Comment by babrubhan** [comment]
> I have ran the setup.py but I still get the error :
> 
> > AttributeError: 'Alpr' object has no attribute 'loaded'
> 
> Please help!

You have to run it with install attribute, i.e., python setup.py install
