### ISSUE TITLE
Python binding does not work with pandas

### ISSUE THREAD

**Issue by francofff** [openalpr/openalpr#764]
Working on a Mac 10.14, install the command-line tool from homebrew. 
`alpr --version` returns 2.3.0.
Create a new virtual environment, run `python setup.py install` in `src/binding/python` and then everything works fine. 
However, after install pandas using pip (what actually installed are: numpy-1.15.4 pandas-0.23.4 python-dateutil-2.7.5 pytz-2018.7 six-1.12.0), running the same script will result to error:
```
python licence.py 
Traceback (most recent call last):
  File "licence.py", line 10, in <module>
    alpr = Alpr("us", "/usr/local/Cellar/openalpr/2.3.0_1/share/openalpr/config/openalpr.defaults.conf", "/usr/local/Cellar/openalpr/2.3.0_1/share/openalpr/runtime_data")
  File "/Users/faznky/.virtualenvs/alpr/lib/python3.7/site-packages/openalpr/openalpr.py", line 85, in __init__
    self._recognize_raw_image_func = self._openalprpy_lib.recognizeRawImage
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fecdc40d010, recognizeRawImage): symbol not found
Exception ignored in: <function Alpr.__del__ at 0x106d6d620>
Traceback (most recent call last):
  File "/Users/faznky/.virtualenvs/alpr/lib/python3.7/site-packages/openalpr/openalpr.py", line 258, in __del__
    if self.is_loaded():
  File "/Users/faznky/.virtualenvs/alpr/lib/python3.7/site-packages/openalpr/openalpr.py", line 135, in is_loaded
    if not self.loaded:
AttributeError: 'Alpr' object has no attribute 'loaded'
```

**Comment by Sturm** [comment]
If anyone encounters the same issue - revert openalpr binding to 1.0.0 as it does not requires numpy. It worked for me.

**Comment by cclauss** [comment]
Dup of #533
