### ISSUE TITLE
Segmentation fault with my trained OCR

### ISSUE THREAD

**Issue by dmelo** [openalpr/openalpr#78]
I have trained OCR for brazilian plates. I'm using european detector and most of the european configuration on openalpr.conf (exceptions only regarding to plate size and char size).

When I run `alpr -c br ./pics` , it breaks on the first image triggered by the european detector.

I also tried training an OCR from the font (as instructed on the tesseract page https://code.google.com/p/tesseract-ocr/wiki/TrainingTesseract3).

When I consolidate the traineddata, I get the following output from combine_tessdata:

```
Combining tessdata files
TessdataManager combined tesseract data files.
Offset for type  0 (lbr.config                ) is -1
Offset for type  1 (lbr.unicharset            ) is 140
Offset for type  2 (lbr.unicharambigs         ) is -1
Offset for type  3 (lbr.inttemp               ) is 2237
Offset for type  4 (lbr.pffmtable             ) is 297476
Offset for type  5 (lbr.normproto             ) is 297733
Offset for type  6 (lbr.punc-dawg             ) is -1
Offset for type  7 (lbr.word-dawg             ) is -1
Offset for type  8 (lbr.number-dawg           ) is -1
Offset for type  9 (lbr.freq-dawg             ) is -1
Offset for type 10 (lbr.fixed-length-dawgs    ) is -1
Offset for type 11 (lbr.cube-unicharset       ) is -1
Offset for type 12 (lbr.cube-word-dawg        ) is -1
Offset for type 13 (lbr.shapetable            ) is 301635
Offset for type 14 (lbr.bigram-dawg           ) is -1
Offset for type 15 (lbr.unambig-dawg          ) is -1
Offset for type 16 (lbr.params-model          ) is -1
Output lbr.traineddata created sucessfully.
```

In both cases, alpr is aborting with segmentation fault. Here is the stacktrace.

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff59b2d7b in tesseract::Classify::ComputeCharNormArrays(FEATURE_STRUCT*, INT_TEMPLATES_STRUCT*, unsigned char*, unsigned char*) () from /usr/local/lib/libtesseract.so.3
(gdb) bt
#0  0x00007ffff59b2d7b in tesseract::Classify::ComputeCharNormArrays(FEATURE_STRUCT*, INT_TEMPLATES_STRUCT*, unsigned char*, unsigned char*) () from /usr/local/lib/libtesseract.so.3
#1  0x00007ffff59b7b6b in tesseract::Classify::CharNormTrainingSample(bool, int, tesseract::TrainingSample const&, GenericVector<tesseract::UnicharRating>*) () from /usr/local/lib/libtesseract.so.3
#2  0x00007ffff59da882 in tesseract::TessClassifier::UnicharClassifySample(tesseract::TrainingSample const&, Pix*, int, int, GenericVector<tesseract::UnicharRating>*) () from /usr/local/lib/libtesseract.so.3
#3  0x00007ffff59b5b22 in tesseract::Classify::CharNormClassifier(TBLOB*, tesseract::TrainingSample const&, ADAPT_RESULTS*) () from /usr/local/lib/libtesseract.so.3
#4  0x00007ffff59b5c95 in tesseract::Classify::DoAdaptiveMatch(TBLOB*, ADAPT_RESULTS*) () from /usr/local/lib/libtesseract.so.3
#5  0x00007ffff59b5f24 in tesseract::Classify::AdaptiveClassifier(TBLOB*, BLOB_CHOICE_LIST*) () from /usr/local/lib/libtesseract.so.3
#6  0x00007ffff59ad93d in tesseract::Wordrec::call_matcher(TBLOB*) () from /usr/local/lib/libtesseract.so.3
#7  0x00007ffff59ad986 in tesseract::Wordrec::classify_blob(TBLOB*, char const*, C_COL, BlamerBundle*) () from /usr/local/lib/libtesseract.so.3
#8  0x00007ffff59aabab in tesseract::Wordrec::classify_piece(GenericVector<SEAM*> const&, short, short, char const*, TWERD*, BlamerBundle*) () from /usr/local/lib/libtesseract.so.3
#9  0x00007ffff599c08d in tesseract::Wordrec::chop_word_main(WERD_RES*) () from /usr/local/lib/libtesseract.so.3
#10 0x00007ffff59ad821 in tesseract::Wordrec::cc_recog(WERD_RES*) () from /usr/local/lib/libtesseract.so.3
#11 0x00007ffff58eae62 in tesseract::Tesseract::recog_word_recursive(WERD_RES*) () from /usr/local/lib/libtesseract.so.3
#12 0x00007ffff58eaff5 in tesseract::Tesseract::recog_word(WERD_RES*) () from /usr/local/lib/libtesseract.so.3
#13 0x00007ffff58dc160 in tesseract::Tesseract::tess_segment_pass_n(int, WERD_RES*) () from /usr/local/lib/libtesseract.so.3
#14 0x00007ffff58a32a5 in tesseract::Tesseract::match_word_pass_n(int, WERD_RES*, ROW*, BLOCK*) () from /usr/local/lib/libtesseract.so.3
#15 0x00007ffff58a3482 in tesseract::Tesseract::classify_word_pass1(tesseract::WordData*, WERD_RES*) () from /usr/local/lib/libtesseract.so.3
#16 0x00007ffff58a66d6 in tesseract::Tesseract::classify_word_and_language(void (tesseract::Tesseract::*)(tesseract::WordData*, WERD_RES*), tesseract::WordData*) () from /usr/local/lib/libtesseract.so.3
#17 0x00007ffff58a6dea in tesseract::Tesseract::RecogAllWordsPassN(int, ETEXT_DESC*, GenericVector<tesseract::WordData>*) () from /usr/local/lib/libtesseract.so.3
#18 0x00007ffff58a7701 in tesseract::Tesseract::recog_all_words(PAGE_RES*, ETEXT_DESC*, TBOX const*, char const*, int) () from /usr/local/lib/libtesseract.so.3
#19 0x00007ffff589603d in tesseract::TessBaseAPI::Recognize(ETEXT_DESC*) () from /usr/local/lib/libtesseract.so.3
#20 0x00007ffff7b6598b in alpr::OCR::performOCR (this=0x86eaf0, pipeline_data=0x7fffffffd200) at /opt/openalpr/src/openalpr/ocr.cpp:78
#21 0x00007ffff7b3bea4 in alpr::AlprImpl::recognizeFullDetails (this=0x86e4e0, img=..., regionsOfInterest=...) at /opt/openalpr/src/openalpr/alpr_impl.cpp:161
#22 0x00007ffff7b3cef3 in alpr::AlprImpl::recognize (this=0x86e4e0, img=..., regionsOfInterest=...) at /opt/openalpr/src/openalpr/alpr_impl.cpp:304
#23 0x00007ffff7b3cc6e in alpr::AlprImpl::recognize (this=0x86e4e0, pixelData=0xabaa30 "", bytesPerPixel=3, imgWidth=748, imgHeight=480, regionsOfInterest=...) at /opt/openalpr/src/openalpr/alpr_impl.cpp:291
#24 0x00007ffff7b38d71 in alpr::Alpr::recognize (this=0x7fffffffde00, pixelData=0xabaa30 "", bytesPerPixel=3, imgWidth=748, imgHeight=480, regionsOfInterest=...) at /opt/openalpr/src/openalpr/alpr.cpp:59
#25 0x00000000004207a7 in detectandshow (alpr=0x7fffffffde00, frame=..., region=..., writeJson=false) at /opt/openalpr/src/main.cpp:283
#26 0x000000000041f3cf in main (argc=4, argv=0x7fffffffe6d8) at /opt/openalpr/src/main.cpp:251
(gdb) 
```

**Comment by dmelo** [comment]
Here is the Tesseract version:
```
tesseract 3.03
 leptonica-1.70
  libgif 4.1.6(?) : libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : webp 0.4.0
```

**Comment by matthill** [comment]
The crash seems to happen inside Tesseract.  It doesn't like something about that training data.  Can you upload the source data (i.e., the tif and box files)?  I can try running the training program on my machine to see if it works
