### ISSUE TITLE
Can't run python Alprstream sample

### ISSUE THREAD

**Issue by wildnrg** [openalpr/openalpr#834]
I am trying to run the python Alprstream sample from http://doc.openalpr.com/sdk.html#alprstream-api

However I get
Traceback (most recent call last):
  File "alprstream.py", line 2, in <module>
    from alprstream import AlprStream
  File "/home/htran/alprstream.py", line 2, in <module>
    from alprstream import AlprStream
ImportError: cannot import name AlprStream

It seems like the same issue as issue #814, however I actually have a licence, and I have confirmed that the commercial licence is work using the command: alpr and alprdconfig

**Comment by arielweinberger** [comment]
Experiencing the same. Any news?
