### ISSUE TITLE
Alpr class required "recognizeRawImage" function which is doesn't exist

### ISSUE THREAD

**Issue by Friday97** [openalpr/openalpr#838]
>>> from openalpr import Alpr 
>>> alpr = Alpr("us", "/etc/openalpr/openalpr.conf", "/usr/share/openalpr/runtime_data") Traceback (most recent call last):   File "<stdin>", line 1, in <module>   
File "/usr/local/lib/python3.5/dist-packages/openalpr/openalpr.py", line 93, in __init__     self._recognize_raw_image_func = self._openalprpy_lib.recognizeRawImage   
File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__     
func = self.__getitem__(name)  
File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__     func = self._FuncPtr((name_or_ordinal, self)) 
AttributeError: /usr/lib/libopenalprpy.so: undefined symbol: recognizeRawImage

**Comment by eltonfernando** [comment]
same problem as windows, in linux it worked! did you find the solution?
