### ISSUE TITLE
openalpr python 2.7 rpi4 undefined symbol openalpr_init

### ISSUE THREAD

**Issue by mjbedford** [openalpr/openalpr#899]
I have openalpr installed and the cli works and I have moved on to try and use the python binding but I get the following error when I cal Aplr()

Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from openalpr import Alpr
>>> alpr = Alpr("us","/etc/openalpr/openalpr.conf", "/usr/share/openalpr/runtime_data")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python2.7/site-packages/openalpr/openalpr.py", line 91, in __init__
    self._initialize_func = self._openalprpy_lib.openalpr_init
  File "/usr/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libopenalpr.so.2: undefined symbol: openalpr_init
>>>

**Comment by hippoduck** [comment]
Is there a fix for this?

**Comment by Tormund1985** [comment]
same for me...
