### ISSUE TITLE
AttributeError: 'Alpr' object has no attribute 'loaded'

### ISSUE THREAD

**Issue by JecintaMulongo** [openalpr/openalpr#913]
I encountered this error while running openalpr in pycharm ubuntu:

AttributeError: /usr/lib/libopenalpr.so.2: undefined symbol: openalpr_add_encoded_image_to_batch
Exception ignored in: <bound method Alpr.del of <openalpr.openalpr.Alpr object at 0x7f1ef1434d68>>
Traceback (most recent call last):
File "/virtualenvs/cv/lib/python3.6/site-packages/openalpr/openalpr.py", line 159, in del
if self.is_loaded():
File "/.virtualenvs/cv/lib/python3.6/site-packages/openalpr/openalpr.py", line 212, in is_loaded
if not self.loaded:
AttributeError: 'Alpr' object has no attribute 'loaded'

any solution

**Comment by wesimet** [comment]
Same Problem

**Comment by mandza** [comment]
Could you provide code you run? Not just error.
Because this error says that you did not provide needed attributes to alpr command

**Comment by cclauss** [comment]
Dup of #533
