### ISSUE TITLE
Installed openalpr.py is different than openalpr.py found in bindings/python directory.

### ISSUE THREAD

**Issue by jordan-bonecutter** [openalpr/openalpr#916]
I was having an issue where using openalpr from python only worked if I was in the bindings/python directory. After stepping through the Alpr constructor, I noticed that the file installed for python at /home/username/.local/lib/python3.8/site-packages/openalpr/openalpr.py differed from openalpr/src/bindings/python/openalpr/openalpr.py. After replacing the installed file with the file found in the bindings directory everything worked fine. For more information, I first compiled using make. Then to install the python binding I navigated into the correct directory and ran make, sudo make install, and sudo python ./setup install which I believe is the correct procedure. The error I got after running this was: 

Traceback (most recent call last):
  File "./lpdetector.py", line 27, in <module>
    main()
  File "./lpdetector.py", line 21, in main
    detector = LicensePlateDetector()
  File "./lpdetector.py", line 10, in __init__
    self.alpr = Alpr('us', '/lib/', '')
  File "/home/jordan/.local/lib/python3.8/site-packages/openalpr/openalpr.py", line 95, in __init__
    self._add_encoded_image_to_batch_func = self._openalprpy_lib.openalpr_add_encoded_image_to_batch
  File "/usr/lib64/python3.8/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/usr/lib64/python3.8/bdb.py", line 174, in dispatch_exception
    if self.quitting: raise BdbQuit
bdb.BdbQuit
Exception ignored in: <function Alpr.__del__ at 0x7ff647b809d0>
Traceback (most recent call last):
  File "/home/jordan/.local/lib/python3.8/site-packages/openalpr/openalpr.py", line 159, in __del__
  File "/home/jordan/.local/lib/python3.8/site-packages/openalpr/openalpr.py", line 212, in is_loaded
AttributeError: 'Alpr' object has no attribute 'loaded

**Comment by cclauss** [comment]
Dup of #533
